apiVersion: v1
name: bc-wallet
description: BC Wallet services with PostgreSQL and RabbitMQ
version: 0.1.0
dependencies:
  - name: postgresql
    version: "12.5.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: "11.16.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled