nameOverride: ""
fullnameOverride: "bc-wallet"

api_server:
  name: bc-wallet-api-server
  image:
    repository: ghcr.io/getmoin/bc-wallet-api-server
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  replicaCount: 1
  labelOverride: ""
  port: 3000
  path: /
  env:
    APP_NAME: bc-wallet-api
    LOG_LEVEL: debug
    DB_PORT: "5432"
    DB_NAME: wallet-db
    DB_USERNAME: wallet-user
    CORS_DISABLED: true
    ALLOW_ORIGINS: "*"
    ALLOW_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
    ALLOW_HEADERS: "Content-Type, Authorization"
    ALLOW_CREDENTIALS: "true"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"

traction_adapter:
  name: bc-wallet-traction-adapter
  image:
    repository: ghcr.io/getmoin/bc-wallet-traction-adapter
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labelOverride: ""
  port: 3000
  path: /traction
  env:
    APP_NAME: bc-wallet-traction-adapter
    LOG_LEVEL: debug
    NODE_PORT: 3000
    RABBITMQ_PORT: 5672
    RABBITMQ_USER: guest
    RABBITMQ_VHOST: /
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    annotations: {}
    automountServiceAccountToken: true
    name: ""
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"

showcase_creator:
  name: bc-wallet-showcase-creator
  image:
    repository: ghcr.io/getmoin/bc-wallet-showcase-creator
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  replicaCount: 1
  labelOverride: ""
  port: 3050
  path: /
  env:
    APP_NAME: bc-wallet-showcase-creator
    LOG_LEVEL: debug
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3050
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"

demo_web:
  name: bc-wallet-demo-web
  image:
    repository: ghcr.io/getmoin/bc-wallet-demo-web
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  replicaCount: 1
  labelOverride: ""
  port: 80
  path: /
  env:
    APP_NAME: bc-wallet-demo-web
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 80
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"

demo_server:
  name: bc-wallet-demo-server
  image:
    repository: ghcr.io/getmoin/bc-wallet-demo-server
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  replicaCount: 1
  labelOverride: ""
  port: 3000
  path: /
  env:
    APP_NAME: bc-wallet-demo-server
    LOG_LEVEL: debug
    TENANT_ID: "xyz"
    API_KEY: "xyz"
    TRACTION_URL: "https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca"
    TRACTION_DID: "xyz"
    BASE_ROUTE: "/digital-trust/showcase"
    WEBHOOK_SECRET: "xyz"
    STUDENT_VERSION: "1.6"
    LAWYER_VERSION: "1.54"
    PERSON_VERSION: "1.3"
    BUSINESS_VERSION: "1.0.0"
    NODE_ENV: "production"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"

# Global ingress settings
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: bcshowcase-api.dev.nborbit.ca
      paths:
        - path: /
          pathType: Prefix
          service: api-server
    - host: bcshowcase-traction.dev.nborbit.ca
      paths:
        - path: /
          pathType: Prefix
          service: traction-adapter
    - host: bcshowcase-ui.dev.nborbit.ca
      paths:
        - path: /
          pathType: Prefix
          service: showcase-creator
    - host: bcshowcase-demo-web.dev.nborbit.ca
      paths:
        - path: /
          pathType: Prefix
          service: demo-web
    - host: bcshowcase-demo-server.dev.nborbit.ca
      paths:
        - path: /
          pathType: Prefix
          service: demo-server
  tls:
    - secretName: bc-wallet-tls
      hosts:
        - bcshowcase-api.dev.nborbit.ca
        - bcshowcase-traction.dev.nborbit.ca
        - bcshowcase-ui.dev.nborbit.ca
        - bcshowcase-demo-web.dev.nborbit.ca
        - bcshowcase-demo-server.dev.nborbit.ca

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: "wallet-user"
    database: "wallet-db"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

rabbitmq:
  enabled: true
  auth:
    username: "guest"
    password: ""
    secretKeys:
      passwordKey: "rabbitmq-password"
      erlangCookieKey: "rabbitmq-erlang-cookie"
  plugins: "rabbitmq_management"
  extraConfiguration: |
    management.listener.port = 15672
    management.listener.ssl = false
  service:
    ports:
      amqp: 5672
      management: 15672
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  replicaCount: 1
  pdb:
    create: true
    minAvailable: 1

global:
  namespaceOverride: ""

debug: true  # Enable debug mode to create the debug-helper ConfigMap