{{- $authtokenSecretName := include "bc-wallet.authtoken.secret.name" . -}}
{{- $authtokenSecret := (lookup "v1" "Secret" .Release.Namespace $authtokenSecretName) -}}
{{- if not $authtokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bc-wallet.authtoken.secret.name" . }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  token: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "bc-wallet.authtoken.secret.name" .) "Key" "token" "Length" 32) }}
{{- end }}