{{- if or (and .Values.api_server.enabled .Values.api_server.networkPolicy.enabled) (and .Values.traction_adapter.enabled .Values.traction_adapter.networkPolicy.enabled) }}
# Default deny all ingress traffic except what's explicitly allowed
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: credential-showcase
    {{- include "credential-showcase.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: []
{{- end }}